spring:
  application:
    name: Junit Example
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  datasource:
    url: jdbc:h2:mem:junit-example-db
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: false
    
  h2:
    console:
      enabled: true
    
server:
  port: 8080
      
logging:
  file:
    path: ${LOGGING_FILE_PATH:bin/logs}
    
management.endpoint.health.show-details: always